FROM golang:1.17-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /bia-consumption
FROM alpine:latest  

WORKDIR /app

COPY --from=build /bia-consumption .

EXPOSE 8080

CMD ["./bia-consumption"]

# first time
# CMD ["./bia-consumption runMigration"]
